name: Build Firmware 

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Clone QMK
      run: |
        cd .. && git clone --depth 1 https://github.com/qmk/qmk_firmware.git
        cd qmk_firmware && make git-submodule
    - name: Install dependencies
      run: cd ../qmk_firmware && pip3 install -r requirements-dev.txt
    - name: Compile Keyboard Firmware
      run: |
        cd ..  && cp -r gingham-haptic-oled/ qmk_firmware/keyboards/yiancardesigns/gingham/keymaps/
        cd qmk_firmware
        make yiancardesigns/gingham:gingham-haptic-oled
    - name: Copy Firmware
      run: |
        cd .. && cp qmk_firmware/yiancardesigns_gingham_gingham-haptic-oled.hex gingham-haptic-oled/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: gingham-haptic-oled-firmware.hex
        path: yiancardesigns_gingham_gingham-haptic-oled.hex
